export const SHOP_PRODUCTS = [
  {
    id: 'nike-tracksuit',
    name: 'Nike Air Tracksuit',
    price: 70,
    condition: 'new',
    img: '/shop/nike-tracksuit-black.jpeg',
    images: ['/shop/nike-tracksuit-black.jpeg', '/shop/nike-tracksuit-blue.jpeg'],
    badge: 'NEW',
    badgeColor: '#C8F135',
    badgeText: '#0D0D0D',
    category: 'Clothing',
    description: 'Premium Nike Air full tracksuit — jacket + pants. Available in black and blue colourways.',
  },
  {
    id: 'asics-shoes',
    name: 'Asics Tennis Shoes',
    price: 140,
    condition: 'new',
    img: '/shop/asics-pink.jpeg',
    images: ['/shop/asics-pink.jpeg', '/shop/asics-white-blue.jpeg', '/shop/asics-white-green.jpeg', '/shop/asics-white-orange.jpeg'],
    badge: 'NEW',
    badgeColor: '#C8F135',
    badgeText: '#0D0D0D',
    category: 'Shoes',
    description: 'Professional Asics court shoes. Multiple colourways available — pink, white/blue, white/green, white/orange.',
  },
  {
    id: 'odea-balls',
    name: 'Odea Tennis Balls + Dampeners',
    price: 195,
    condition: 'new',
    img: '/shop/odea-balls-box.jpeg',
    images: ['/shop/odea-balls-box.jpeg', '/shop/odea-balls-side.jpeg', '/shop/dampeners.jpeg'],
    badge: 'BUNDLE',
    badgeColor: '#3B82F6',
    badgeText: '#FFFFFF',
    category: 'Accessories',
    description: 'Full box of Odea Passion Tour tennis balls (ITF approved) plus a collection of colourful dampeners.',
  },
  {
    id: 'babolat-racket',
    name: 'Babolat Racket',
    price: 250,
    condition: 'new',
    img: '/shop/babolat-rafa-aero.jpeg',
    images: ['/shop/babolat-rafa-aero.jpeg', '/shop/babolat-pure-aero.jpeg', '/shop/babolat-pure-drive.jpeg', '/shop/babolat-pure-strike.jpeg', '/shop/babolat-wimbledon.jpeg'],
    badge: 'NEW',
    badgeColor: '#C8F135',
    badgeText: '#0D0D0D',
    category: 'Rackets',
    description: 'Genuine Babolat rackets — Pure Aero Rafa, Pure Aero, Pure Drive, Pure Strike, and Wimbledon editions available.',
  },
  {
    id: 'head-radical',
    name: 'Head Radical',
    price: 300,
    condition: 'new',
    img: '/shop/head-radical-label.jpeg',
    images: ['/shop/head-radical-label.jpeg', '/shop/head-radical-wrapped.jpeg', '/shop/head-radical-frame.jpeg'],
    badge: 'NEW',
    badgeColor: '#C8F135',
    badgeText: '#0D0D0D',
    category: 'Rackets',
    description: 'HEAD Radical MP — radical versatility. 98" head, 300g, as used by Taylor Fritz. Brand new in wrapping.',
  },
]
